Добавил новые suspend-методы классы Request и Response DTO модели м и тд
ElchinGasymov/practicum-android-diploma pull request #106
Opened 2024-08-16 10:24 UTC by G-dev-ui

2024-08-16 11:44 UTC, AnShok requested changes

2024-08-16 11:44 UTC, AnShok commented on app/src/main/java/ru/practicum/android/diploma/data/dto/components/CountryDto.kt
> +    val id: Int,
Проверь пожалуйста, Id string

В остальных местах тоже

2024-08-16 14:44 UTC, ElchinGasymov commented on app/src/main/java/ru/practicum/android/diploma/data/dto/CountriesRequest.kt
> +data object CountriesRequest
Точно должен быть пустым?

2024-08-16 14:44 UTC, ElchinGasymov commented on app/src/main/java/ru/practicum/android/diploma/domain/models/Country.kt
> +        private const val serialVersionUID = 1L
Чет не нашел такого в доке это зачем?

2024-08-17 08:49 UTC, ElchinGasymov requested changes

2024-08-17 08:49 UTC, ElchinGasymov commented on app/src/main/java/ru/practicum/android/diploma/data/network/HHApiService.kt
> +    suspend fun getRegions(@Path("area_id") areaId: Int): Response<RegionListDto>
areaId должен быть стрингом согласно доке
<img width="1445" alt="Снимок экрана 2024-08-17 в 11 37 57" src="https://github.com/user-attachments/assets/0842e4e8-c331-48c8-9b05-65bca73b16a1">

2024-08-17 09:30 UTC, AndreyRyabitckiy approved these changes

2024-08-17 09:55 UTC, ElchinGasymov requested changes

2024-08-17 09:55 UTC, ElchinGasymov commented on app/src/main/java/ru/practicum/android/diploma/data/network/RetrofitNetworkClient.kt
> +        val networkResponse = hhApiService.getRegions(dto.id.toString())
Изменить в regionrequest

2024-08-18 06:36 UTC, AnShok approved these changes

2024-08-18 06:55 UTC, ElchinGasymov approved these changes

2024-08-18 06:55 UTC, merged