Граф нафигации и основные экраны
ElchinGasymov/practicum-android-diploma pull request #19
Opened 2024-08-03 08:18 UTC by AnShok

2024-08-03 12:23 UTC, Logomann approved these changes

2024-08-03 13:42 UTC, AndreyRyabitckiy approved these changes

2024-08-03 13:50 UTC, ElchinGasymov requested changes

2024-08-03 13:50 UTC, ElchinGasymov commented on app/src/main/java/ru/practicum/android/diploma/ui/fragments/FavouritesFragment.kt
> +        return inflater.inflate(R.layout.fragment_favourites, container, false)
Давай во всех фрагментах заменим конструкции типа R.layout.fragment_favourites и view.findViewById на ViewBinding, как это делали на курсе, это даже есть в требованиях
<img width="680" alt="Снимок экрана 2024-08-03 в 16 30 08" src="https://github.com/user-attachments/assets/0877492f-394b-463a-a14a-074070721901">

2024-08-03 13:50 UTC, ElchinGasymov commented on app/src/main/java/ru/practicum/android/diploma/ui/fragments/FilterFragment.kt
> +        view.findViewById<Button>(R.id.button_back_to_search_from_filter).setOnClickListener {
Аналогично + в остальных fragment

2024-08-03 13:50 UTC, ElchinGasymov commented on app/src/main/res/layout/activity_root.xml
> -    tools:context=".ui.root.RootActivity">
Зачем убрал эту строчку?

2024-08-03 13:50 UTC, ElchinGasymov commented on app/src/main/res/layout/activity_root.xml
> +    android:orientation="vertical">
```suggestion
    android:orientation="vertical">
```
Эта строчка точно нужна?

2024-08-03 13:50 UTC, ElchinGasymov commented on app/src/main/res/layout/activity_root.xml
> +        tools:ignore="MissingConstraints" />
Давай вместо tools:ignore="MissingConstraints" все таки укажем нужные констрэйнты, например левый, верхний, правый - parent

2024-08-03 13:50 UTC, ElchinGasymov commented on app/src/main/res/layout/fragment_filter.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Может лучше все описывать не на LinearLayout а на ConstraintLayout? Давай обсудим в телеге

2024-08-03 13:50 UTC, ElchinGasymov commented on app/src/main/res/navigation/main_navigation_graph.xml
> +        android:id="@+id/team_screen"
```suggestion
        android:id="@+id/teamFragment"
```

2024-08-03 13:50 UTC, ElchinGasymov commented on app/src/main/res/navigation/main_navigation_graph.xml
> +        android:id="@+id/favorite_screen"
```suggestion
        android:id="@+id/favoriteFragment"
```

2024-08-03 13:50 UTC, ElchinGasymov commented on app/src/main/res/navigation/main_navigation_graph.xml
> +        android:id="@+id/main_screen"
```suggestion
        android:id="@+id/mainFragment"
```

2024-08-03 15:53 UTC, AnShok commented on app/src/main/res/layout/activity_root.xml
> +    android:orientation="vertical">
в ConstraintLayout нет
Уберу

2024-08-03 16:30 UTC, AnShok commented
@ElchinGasymov, все исправил

2024-08-04 08:39 UTC, ElchinGasymov approved these changes

2024-08-04 08:39 UTC, merged