Верстка экрана поиска вакансий
ElchinGasymov/practicum-android-diploma pull request #46
Opened 2024-08-06 14:34 UTC by AnShok

2024-08-06 16:09 UTC, Logomann approved these changes

2024-08-07 06:49 UTC, ElchinGasymov requested changes

2024-08-07 06:49 UTC, ElchinGasymov commented on app/src/main/res/drawable/shape_search_item.xml
> +    <corners android:radius="12dp"/>
Вынесем в dimens?

2024-08-07 06:49 UTC, ElchinGasymov commented on app/src/main/res/drawable/shape_search_edit_text.xml
> +    <corners android:radius="12dp" />
Dimens

2024-08-07 06:49 UTC, ElchinGasymov commented on app/src/main/res/drawable/shape_text_under_search.xml
> +    <corners android:radius="12dp" />
и еще

2024-08-07 06:49 UTC, ElchinGasymov commented on app/src/main/res/layout/fragment_search.xml
> +        style="@style/tool_bar"
```suggestion
        style="@style/toolbar"
```

2024-08-07 07:13 UTC, ElchinGasymov approved these changes

2024-08-07 07:13 UTC, merged