Career hub filter fragment
ElchinGasymov/practicum-android-diploma pull request #98
Opened 2024-08-15 11:59 UTC by AnShok

2024-08-15 13:41 UTC, ElchinGasymov requested changes

2024-08-15 13:41 UTC, ElchinGasymov commented on app/src/main/java/ru/practicum/android/diploma/ui/fragments/FilterFragment.kt
> +        binding.applyButton.setOnClickListener { saveAndNavigateUp() }
я бы вместо saveAndNavigateUp назвал как то по другому, вместо up название экрана. либо просто saveFilters как то так. потому что up как то не совсем понятно куда именно

2024-08-15 13:41 UTC, ElchinGasymov commented on app/src/main/java/ru/practicum/android/diploma/ui/fragments/FilterPlaceOfWorkFragment.kt
> +        binding.applyButton.setOnClickListener { saveAndNavigateUp() }
тут то же про нэйминг, и исправь плиз в остальных местах где это еще есть

2024-08-15 13:41 UTC, ElchinGasymov commented on app/src/main/res/layout/fragment_select_place_of_work.xml
> +        android:layout_marginBottom="@dimen/dimen_8dp"
По макетам тут 24dp

2024-08-15 13:41 UTC, ElchinGasymov commented on app/src/main/res/layout/industry_item_view.xml
> +    <RadioButton
Цвет этого элемента не как в макетах

2024-08-15 13:41 UTC, ElchinGasymov commented on app/src/main/res/values/styles.xml
> +        <!--<item name="android:textColorHint">@color/gray</item>-->
Кажется эта строчка не нужна

2024-08-15 16:49 UTC, AndreyRyabitckiy approved these changes

2024-08-16 07:41 UTC, ElchinGasymov approved these changes

2024-08-16 07:41 UTC, merged